// <auto-generated />
using System;
using LaPecosa.Infraestructura.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LaPecosa.Infraestructura.Datos.Migraciones
{
    [DbContext(typeof(ContextoLaPecosa))]
    [Migration("20261010025958_HermanosDeLaCuenta")]
    partial class HermanosDeLaCuenta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.AsignacionEntrenadorCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioRolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("CategoriaId", "UsuarioRolId")
                        .IsUnique();

                    b.HasIndex("UsuarioRolId", "Activa");

                    b.ToTable("AsignacionesEntrenadorCategoria", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Usada")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "Anio")
                        .IsUnique()
                        .HasDatabaseName("IX_Categorias_ClubId_Anio");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorAcento")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ColorPrincipal")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("CorreoContacto")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("EstadoCambiadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EstadoCambiadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Sede")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VersionEscudo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NombreNormalizado")
                        .IsUnique()
                        .HasDatabaseName("IX_Clubes_NombreNormalizado");

                    b.ToTable("Clubes", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.DocumentoJugador", b =>
                {
                    b.Property<Guid>("UsuarioRolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("SubidoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TamanoBytes")
                        .HasColumnType("integer");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("UsuarioRolId", "Documento");

                    b.HasIndex("ClubId");

                    b.ToTable("DocumentosJugador", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.EntrenadorEquipo", b =>
                {
                    b.Property<Guid>("AsignacionEntrenadorCategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.HasKey("AsignacionEntrenadorCategoriaId", "EquipoId");

                    b.HasIndex("ClubId");

                    b.HasIndex("EquipoId");

                    b.ToTable("EntrenadoresEquipo", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("CategoriaId", "NombreNormalizado")
                        .IsUnique()
                        .HasDatabaseName("IX_Equipos_CategoriaId_NombreNormalizado")
                        .HasFilter("\"Activo\"");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.EscudoClub", b =>
                {
                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("ClubId");

                    b.ToTable("EscudosClub", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.FichaJugador", b =>
                {
                    b.Property<Guid>("UsuarioRolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Alergias")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmergenciaCelular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmergenciaNombre")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("EmergenciaParentesco")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Enfermedades")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntidadSalud")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("GrupoSanguineo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LugarAtencion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Medicamentos")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UltimoCambioEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UltimoCambioPorNombre")
                        .IsRequired()
                        .HasMaxLength(161)
                        .HasColumnType("character varying(161)");

                    b.Property<Guid?>("UltimoCambioPorUsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioRolId");

                    b.HasIndex("ClubId");

                    b.HasIndex("UltimoCambioPorUsuarioId");

                    b.ToTable("FichasJugador", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.FotoPerfil", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("UsuarioId");

                    b.ToTable("FotosPerfil", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Invitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnuladaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreadaPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoEnvio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VenceEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ClubId", "Correo");

                    b.ToTable("Invitaciones", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.JugadorEquipo", b =>
                {
                    b.Property<Guid>("UsuarioRolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioRolId", "EquipoId");

                    b.HasIndex("ClubId");

                    b.HasIndex("EquipoId");

                    b.ToTable("JugadoresEquipo", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.SolicitudRecuperacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("VenceEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitudesRecuperacion", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("boolean");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContrasenaHash")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("CorreoNormalizado")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsDesarrollador")
                        .HasColumnType("boolean");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("NombreResponsable")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("SelloSeguridad")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionFoto")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorreoNormalizado")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_CorreoNormalizado");

                    b.HasIndex("EsDesarrollador")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_EsDesarrollador")
                        .HasFilter("\"EsDesarrollador\" = TRUE");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("AgregadoDesdeUsuarioRolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("AprobadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AprobadoPorNombre")
                        .HasMaxLength(161)
                        .HasColumnType("character varying(161)");

                    b.Property<Guid?>("AprobadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstadoIngreso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("RetiradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetiradoPorNombre")
                        .HasMaxLength(161)
                        .HasColumnType("character varying(161)");

                    b.Property<Guid?>("RetiradoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RolDeIngreso")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgregadoDesdeUsuarioRolId");

                    b.HasIndex("AprobadoPorUsuarioId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("NumeroDocumento");

                    b.HasIndex("RetiradoPorUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ClubId", "CategoriaId");

                    b.HasIndex("ClubId", "EstadoIngreso");

                    b.HasIndex("ClubId", "NumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("IX_UsuariosRol_ClubId_NumeroDocumento");

                    b.HasIndex("ClubId", "UsuarioId");

                    b.ToTable("UsuariosRol", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.AsignacionEntrenadorCategoria", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Asignaciones")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPecosa.Dominio.Entidades.UsuarioRol", "UsuarioRol")
                        .WithMany()
                        .HasForeignKey("UsuarioRolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Club");

                    b.Navigation("UsuarioRol");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Categoria", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.DocumentoJugador", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPecosa.Dominio.Entidades.UsuarioRol", "UsuarioRol")
                        .WithMany()
                        .HasForeignKey("UsuarioRolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("UsuarioRol");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.EntrenadorEquipo", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.AsignacionEntrenadorCategoria", "Asignacion")
                        .WithMany("Equipos")
                        .HasForeignKey("AsignacionEntrenadorCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPecosa.Dominio.Entidades.Equipo", "Equipo")
                        .WithMany("Entrenadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("Club");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Equipo", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany("Equipos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.EscudoClub", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithOne()
                        .HasForeignKey("LaPecosa.Dominio.Entidades.EscudoClub", "ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.FichaJugador", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPecosa.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UltimoCambioPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LaPecosa.Dominio.Entidades.UsuarioRol", "UsuarioRol")
                        .WithOne()
                        .HasForeignKey("LaPecosa.Dominio.Entidades.FichaJugador", "UsuarioRolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("UsuarioRol");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.FotoPerfil", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("LaPecosa.Dominio.Entidades.FotoPerfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Invitacion", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.JugadorEquipo", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPecosa.Dominio.Entidades.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPecosa.Dominio.Entidades.UsuarioRol", "UsuarioRol")
                        .WithMany("Equipos")
                        .HasForeignKey("UsuarioRolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Equipo");

                    b.Navigation("UsuarioRol");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.SolicitudRecuperacion", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.UsuarioRol", "AgregadoDesde")
                        .WithMany()
                        .HasForeignKey("AgregadoDesdeUsuarioRolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LaPecosa.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AprobadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LaPecosa.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPecosa.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("RetiradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LaPecosa.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgregadoDesde");

                    b.Navigation("Categoria");

                    b.Navigation("Club");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.AsignacionEntrenadorCategoria", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Categoria", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Equipo", b =>
                {
                    b.Navigation("Entrenadores");

                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
