// <auto-generated />
using System;
using LaPecosa.Infraestructura.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LaPecosa.Infraestructura.Datos.Migraciones
{
    [DbContext(typeof(ContextoLaPecosa))]
    [Migration("20261007200542_Invitaciones")]
    partial class Invitaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorAcento")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ColorPrincipal")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("CorreoContacto")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("EstadoCambiadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EstadoCambiadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Sede")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VersionEscudo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NombreNormalizado")
                        .IsUnique()
                        .HasDatabaseName("IX_Clubes_NombreNormalizado");

                    b.ToTable("Clubes", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Invitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnuladaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreadaPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoEnvio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VenceEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ClubId", "Correo");

                    b.ToTable("Invitaciones", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.SolicitudRecuperacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("VenceEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitudesRecuperacion", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("boolean");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContrasenaHash")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("CorreoNormalizado")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsDesarrollador")
                        .HasColumnType("boolean");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<Guid>("SelloSeguridad")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionFoto")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorreoNormalizado")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_CorreoNormalizado");

                    b.HasIndex("EsDesarrollador")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_EsDesarrollador")
                        .HasFilter("\"EsDesarrollador\" = TRUE");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstadoIngreso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NumeroDocumento");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ClubId", "NumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("IX_UsuariosRol_ClubId_NumeroDocumento");

                    b.HasIndex("ClubId", "UsuarioId");

                    b.ToTable("UsuariosRol", (string)null);
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.Invitacion", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.SolicitudRecuperacion", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LaPecosa.Dominio.Entidades.UsuarioRol", b =>
                {
                    b.HasOne("LaPecosa.Dominio.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPecosa.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
